name: Simple PR Test
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "master" ]
jobs:
  echo_test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello
        run: echo "Hello from PR!"
